/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.DAO.TraderDAO;
import model.Trader;
import util.UtilServices;

/**
 *
 * @author alanm
 */
public class LoginTradeUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginTradeUI
     */
    public LoginTradeUI() {
        initComponents();
        this.maskFields();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        bt_cancel = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();
        txtBirthday = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_login.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CPF");

        jLabel2.setText("Senha:");

        jLabel3.setText("Data de Nascimento:");

        bt_login.setText("Login");
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        bt_cancel.setText("Cancelar");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_loginLayout.createSequentialGroup()
                        .addComponent(bt_cancel)
                        .addGap(18, 18, 18)
                        .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pnl_loginLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_cancel, bt_login});

        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_login)
                    .addComponent(bt_cancel))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pnl_loginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_cancel, bt_login});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        // TODO add your handling code here:
        WellcomeTradeUI wellcome = new WellcomeTradeUI();
        wellcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        Trader trader;
        TraderDAO tDAO = new TraderDAO();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String password = new String(txtPassword.getPassword()).trim();
        String cpf = UtilServices.deformCPF(txtCPF.getText());
        
        try {
            if(( password.isEmpty() || password == null)
                    || (txtBirthday.getText().isEmpty() || txtBirthday.getText() == null || txtBirthday.getText().equals("__/__/____"))
                    || (cpf.isEmpty() || cpf == null || txtCPF.getText().equals("___-___-___.__")))
            {
                JOptionPane.showMessageDialog(null,
                        "Todos os campos são obrigatórios. \n"
                                + "Tente novamente.", //mensagem
                        "Login", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                trader = tDAO.getTraderCPF(cpf);

                if(trader == null)
                {
                    JOptionPane.showMessageDialog(null,
                            "CPF não cadastrado. \n"
                                    + "Confira os dados inseridos.", //mensagem
                            "Login", // titulo da janela
                            JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    if(trader.getPassword().equals(password) && trader.getDt_birthday().equals(formato.parse(txtBirthday.getText())))
                    {
                        WalletTradeUI walletUI = new WalletTradeUI(trader);
                        walletUI.setVisible(true);
                        dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,
                            "Dados incorretos. \n"
                                    + "Tente novamente.", //mensagem
                            "Login", // titulo da janela
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_bt_loginActionPerformed
    
    private void maskFields()
    {
        //Container janela = getContentPane();
             setLayout(null);

             //Define as máscaras
             MaskFormatter mascaraCpf = null;
             MaskFormatter mascaraData = null;

             try{
                    //mascaraCep = new MaskFormatter("#####-###");
                   // mascaraTel = new MaskFormatter("(##)####-####");
                    mascaraCpf = new MaskFormatter("###.###.###-##");
                    mascaraData = new MaskFormatter("##/##/####");
                   // mascaraCep.setPlaceholderCharacter('_');
                   // mascaraTel.setPlaceholderCharacter('_');
                    mascaraCpf.setPlaceholderCharacter('_');
                    mascaraData.setPlaceholderCharacter('_');
             }
             catch(ParseException excp) {
                    System.err.println("Erro na formatação: " + excp.getMessage());
                    System.exit(-1);
             }
             txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraCpf));
             txtBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
             //Seta as máscaras nos objetos JFormattedTextField
             //JFormattedTextField jFormattedTextCep = new JFormattedTextField(mascaraCep);
             //JFormattedTextField jFormattedTextTel = new JFormattedTextField(mascaraTel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTradeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JFormattedTextField txtBirthday;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
