/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Assets;
import model.DAO.AssetsDAO;
import model.DAO.WalletDAO;
import model.Wallet;
import util.UtilServices;

/**
 *
 * @author alanm
 */
public class RescueAssetsUI extends javax.swing.JFrame {
    
    NumberFormat _nf;
    WalletDAO _wDAO;
    Wallet _wallet;
    AssetsDAO _aDAO;
    Assets _assets;
    /**
     * Creates new form RescueAssetsUI
     * @param a
     */
    public RescueAssetsUI(Assets a) {
        initComponents();
        this.loadComponents(a);
    }

    private RescueAssetsUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblAsset = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuatity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbRescue = new javax.swing.JComboBox<>();
        btnRescue = new javax.swing.JButton();
        bntCancel = new javax.swing.JButton();
        txtValueRescue = new util.JMoneyField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Ativo:");

        lblAsset.setText("jLabel3");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Valor de Venda:");

        jLabel6.setText("Resgate:");

        cmbRescue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRescue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRescueActionPerformed(evt);
            }
        });

        btnRescue.setText("Resgatar");
        btnRescue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRescueActionPerformed(evt);
            }
        });

        bntCancel.setText("Cancelar");
        bntCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRescue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRescue, 0, 335, Short.MAX_VALUE)
                            .addComponent(txtQuatity)
                            .addComponent(lblAsset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtValueRescue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(bntCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAsset))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbRescue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuatity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValueRescue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnRescue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntCancel)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRescueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRescueActionPerformed
        // TODO add your handling code here:
        if(cmbRescue.getSelectedItem().toString().equals("Total"))
        {
            this.txtQuatity.setEnabled(false);
            this.txtQuatity.setText(String.valueOf(this._assets.getQt_asset()));
            
            this.txtValueRescue.setEnabled(false);
            this.txtValueRescue.setText(this._assets.getVl_amountInvested().toString());
            
        }
        else
        {
            this.txtQuatity.setEnabled(true);
            this.txtQuatity.setText("");
            
            this.txtValueRescue.setEnabled(true);
            this.txtValueRescue.setText("");
        }
    }//GEN-LAST:event_cmbRescueActionPerformed

    private void bntCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelActionPerformed
        AssetsTradeUI assetsUI = AssetsTradeUI.getInstance(this._assets.getWallet());
        assetsUI.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_bntCancelActionPerformed

    private void btnRescueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRescueActionPerformed
        // TODO add your handling code here: -- Selecione --
        try 
        {
           if(cmbRescue.getSelectedItem().toString().equals("-- Selecione --"))
            {
                JOptionPane.showMessageDialog(null,
                            "Selecione o tipo de resgate.\n", //mensagem
                            "Resgate", // titulo da janela
                            JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(cmbRescue.getSelectedItem().toString().equals("Parcial"))
            {
                if(( txtQuatity.getText().isEmpty() || txtQuatity.getText() == null)
                    || (txtValueRescue.getText().equals("0,00")))
                {
                    JOptionPane.showMessageDialog(null,
                        "Você deve informar a quantidade e valor do resgate.\n"
                                + "Tente novamente.", //mensagem
                        "Ativo", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            if(cmbRescue.getSelectedItem().toString().equals("Total"))
            {
                this._wallet.setAmount_invested(this._wallet.getAmount_invested().subtract(this._assets.getVl_amountInvested()));
                this._wDAO.update(this._wallet);

                this._aDAO.delete(this._assets.getId_asset());
                
            }
            else
            {
                int qtd = Integer.parseInt(txtQuatity.getText());
                String cot = this.txtValueRescue.getText();
                cot = cot.replace(".","").replace(",",".");
                BigDecimal cotacao = new BigDecimal(cot);
                BigDecimal montante = cotacao.multiply(BigDecimal.valueOf(qtd));

                if(this._assets.getVl_amountInvested().compareTo(montante) == -1)
                {
                    JOptionPane.showMessageDialog(null,
                        "Montante resgatado maior que o disponível no ativo.\n", //mensagem
                        "Ativo", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                this._assets.setQt_asset(this._assets.getQt_asset()-qtd);
                this._assets.setVl_amountInvested(this._assets.getVl_amountInvested().subtract(montante));

                this._wallet.setAmount_invested(this._wallet.getAmount_invested().subtract(montante));

                this._aDAO.update(this._assets);
                this._wDAO.update(this._wallet);

                JOptionPane.showMessageDialog(null,
                                    "Resgate "+ this._assets.getNm_asset().toUpperCase() + " salvo com sucesso. \n", //mensagem
                                    "Ativo", // titulo da janela
                                    JOptionPane.INFORMATION_MESSAGE);
                
            }  
            } catch (Exception e) {
                Logger.getLogger(InsertAssetsUI.class.getName()).log(Level.SEVERE, null, e);
            }
            this.backAssets();
    }//GEN-LAST:event_btnRescueActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        backAssets();
    }//GEN-LAST:event_formWindowClosed

    private void backAssets()
    {
        AssetsTradeUI assetsUI = AssetsTradeUI.getInstance(_wallet);
        assetsUI.setEnabled(true);
        assetsUI.loadTable();
        this.dispose();
    }

    private void loadCombo()
    {
        Object[] values = {"-- Selecione --","Total","Parcial"};
        UtilServices.loadCombo(cmbRescue, values);
        //this.cmbRescue = new JComboBox(values);
    }
    
     private void loadComponents(Assets a)
    {
        this.loadCombo();
        this.setLocationRelativeTo(null);
        this._wDAO = new WalletDAO();
        this._aDAO = new AssetsDAO();
        this._nf = NumberFormat.getCurrencyInstance();
        this._assets = a;
        this._wallet = a.getWallet();
        this.lblAsset.setText(a.getNm_asset());
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RescueAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RescueAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RescueAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RescueAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RescueAssetsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancel;
    private javax.swing.JButton btnRescue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbRescue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAsset;
    private javax.swing.JTextField txtQuatity;
    private util.JMoneyField txtValueRescue;
    // End of variables declaration//GEN-END:variables
}
