/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Assets;
import model.DAO.AssetsDAO;
import model.DAO.WalletDAO;
import model.Wallet;
import util.UtilServices;

/**
 *
 * @author alanm
 */
public class UpdateAssetsUI extends javax.swing.JFrame {
    
    NumberFormat _nf;
    WalletDAO _wDAO;
    AssetsDAO _aDAO;
    Wallet _wallet;
    Assets _asset;
    /**
     * Creates new form UpdateAssetsUI
     */
    public UpdateAssetsUI(Assets a) {
        initComponents();
        this.loadComponents(a);
    }

    private UpdateAssetsUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNmAsset = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDtBuy = new javax.swing.JFormattedTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValueAsset = new util.JMoneyField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ativo:");

        lblNmAsset.setText("jLabel2");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Cotação:");

        txtDtBuy.setText("jFormattedTextField1");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jLabel5.setText("Data da Compra:");

        txtValueAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueAssetActionPerformed(evt);
            }
        });

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNmAsset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDtBuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtValueAsset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNmAsset))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValueAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDtBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueAssetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueAssetActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        backAssets();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Assets asset = new Assets();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        Date dt_buy;
        
        try {
              
            
            if((txtQuantity.getText().isEmpty() || txtQuantity.getText() == null))
            {
                JOptionPane.showMessageDialog(null,
                        "Informe a quantidade.\n"
                                + "Tente novamente.", //mensagem
                        "Ativo", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if((txtValueAsset.getText().equals("0,00")))
            {
                JOptionPane.showMessageDialog(null,
                        "Informe a cotação.\n"
                                + "Tente novamente.", //mensagem
                        "Ativo", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(!UtilServices.isValidDate(txtDtBuy.getText()))
            {
                JOptionPane.showMessageDialog(null,
                        "Data inválida.\n"
                         + "Tente novamente.", //mensagem
                        "Data", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            if(!UtilServices.isValidDate(txtDtBuy.getText()))
            {
                JOptionPane.showMessageDialog(null,
                        "Data inválida.\n"
                         + "Tente novamente.", //mensagem
                        "Data", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            else
            {
                dt_buy = formato.parse(txtDtBuy.getText());
            }
            DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
            
            if(df.format(dt_buy).equals(df.format(this._asset.getDt_lastBuy())))
            {
                JOptionPane.showMessageDialog(null,
                        "A data informada é anterior à última compra.\n"
                         + "Última compra: " + this._asset.getDt_lastBuy().toString(), //mensagem
                        "Data", // titulo da janela
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            String cot = this.txtValueAsset.getText();
            cot = cot.replace(".","").replace(",",".");
            BigDecimal cotacao = new BigDecimal(cot);
            int qtd = Integer.parseInt(txtQuantity.getText());
            
            this._asset.setDt_lastBuy(dt_buy);
            this._asset.setQt_asset(this._asset.getQt_asset()+qtd);            
            this._asset.setVl_lastBuy(cotacao);
            this._asset.setVl_amountInvested(this._asset.getVl_amountInvested().add(cotacao.multiply(BigDecimal.valueOf(qtd))));       

            this._aDAO.update(this._asset);

            this._wallet.setAmount_invested(this._wallet.getAmount_invested().add(cotacao.multiply(BigDecimal.valueOf(qtd))));

            this._wDAO.update(_wallet);

            JOptionPane.showMessageDialog(null,
                    "Ativo "+ this._asset.getNm_asset().toUpperCase() + " salvo com sucesso. \n", //mensagem
                    "Ativo", // titulo da janela
                    JOptionPane.INFORMATION_MESSAGE);

            this.backAssets();
        } catch (Exception e) {
            Logger.getLogger(InsertAssetsUI.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.backAssets();
    }//GEN-LAST:event_formWindowClosed
    
    
    private void backAssets()
    {
        AssetsTradeUI assetsUI = AssetsTradeUI.getInstance(_wallet);
        assetsUI.setEnabled(true);
        assetsUI.loadTable();
        this.dispose();
    }
    
    private void maskFields()
    {
        setLayout(null);

        MaskFormatter mascaraData = null;
             
        try
        {
            mascaraData = new MaskFormatter("##/##/####");
            mascaraData.setPlaceholderCharacter('_');
        }
        catch(ParseException excp) 
        {
            System.err.println("Erro na formatação: " + excp.getMessage());
            System.exit(-1);
        }
        
        txtDtBuy.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascaraData));
    } 
    
    public void loadComponents(Assets a)
    {
        this.setLocationRelativeTo(null);
        this._wDAO = new WalletDAO();
        this._nf = NumberFormat.getCurrencyInstance();
        this._aDAO = new AssetsDAO();
        this._asset = a;
        this._wallet = a.getWallet();
        this.lblNmAsset.setText(a.getNm_asset());
        this.maskFields();
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAssetsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAssetsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNmAsset;
    private javax.swing.JFormattedTextField txtDtBuy;
    private javax.swing.JTextField txtQuantity;
    private util.JMoneyField txtValueAsset;
    // End of variables declaration//GEN-END:variables
}
